In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("student_performance_prediction.csv")
df = df.dropna()
x = df.iloc[:,1:-1].values
y = df.iloc[:,-1].values
y = np.where(y=="Yes",1,0)
y

array([0, 0, 0, ..., 1, 0, 1])

In [3]:
x.shape

(29446, 5)

In [4]:
y.shape

(29446,)

In [5]:
df.head()

Student ID  Study Hours per Week  Attendance Rate  Previous Grades  \
1     S00002                   9.3             95.3             60.6   
3     S00004                  17.6             76.8             62.4   
4     S00005                   8.8             89.3             72.7   
5     S00006                   8.8             73.8             69.3   
6     S00007                  17.9             38.6             93.6   

  Participation in Extracurricular Activities Parent Education Level Passed  
1                                          No            High School     No  
3                                         Yes               Bachelor     No  
4                                          No                 Master     No  
5                                         Yes            High School    Yes  
6                                          No              Doctorate    Yes

In [6]:
x

array([[9.3, 95.3, 60.6, 'No', 'High School'],
       [17.6, 76.8, 62.4, 'Yes', 'Bachelor'],
       [8.8, 89.3, 72.7, 'No', 'Master'],
       ...,
       [11.3, 66.4, 64.2, 'No', 'Doctorate'],
       [13.1, 65.6, 38.1, 'No', 'Bachelor'],
       [11.8, 55.1, 68.5, 'No', 'Bachelor']], dtype=object)

In [7]:
y

array([0, 0, 0, ..., 1, 0, 1])

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,3] = le.fit_transform(x[:,3])
x

array([[9.3, 95.3, 60.6, 0, 'High School'],
       [17.6, 76.8, 62.4, 1, 'Bachelor'],
       [8.8, 89.3, 72.7, 0, 'Master'],
       ...,
       [11.3, 66.4, 64.2, 0, 'Doctorate'],
       [13.1, 65.6, 38.1, 0, 'Bachelor'],
       [11.8, 55.1, 68.5, 0, 'Bachelor']], dtype=object)

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[-1])],remainder="passthrough")
x = np.array(ct.fit_transform(x))
x

array([[0.0, 0.0, 0.0, ..., 95.3, 60.6, 0],
       [0.0, 1.0, 0.0, ..., 76.8, 62.4, 1],
       [0.0, 0.0, 0.0, ..., 89.3, 72.7, 0],
       ...,
       [0.0, 0.0, 1.0, ..., 66.4, 64.2, 0],
       [0.0, 1.0, 0.0, ..., 65.6, 38.1, 0],
       [0.0, 1.0, 0.0, ..., 55.1, 68.5, 0]], dtype=object)

In [10]:
x[:,-1]

array([0, 1, 0, ..., 0, 0, 0], dtype=object)

In [11]:
from sklearn.model_selection import train_test_split
x_train ,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)
x_train


array([[0.0, 0.0, 0.0, ..., 105.1, 74.9, 1],
       [0.0, 0.0, 1.0, ..., 81.6, 56.4, 0],
       [0.0, 0.0, 0.0, ..., 102.5, 98.0, 1],
       ...,
       [0.0, 0.0, 0.0, ..., 65.7, 55.9, 0],
       [0.0, 1.0, 0.0, ..., 64.1, 84.1, 1],
       [0.0, 0.0, 0.0, ..., 56.3, 31.0, 1]], dtype=object)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [13]:
x_train

array([[-0.50157819, -0.50515539, -0.5015119 , ...,  1.4610821 ,
         0.57336988,  0.99915132],
       [-0.50157819, -0.50515539,  1.99397063, ...,  0.30971003,
        -0.54854838, -1.0008494 ],
       [-0.50157819, -0.50515539, -0.5015119 , ...,  1.33369625,
         1.97425159,  0.99915132],
       ...,
       [-0.50157819, -0.50515539, -0.5015119 , ..., -0.46930341,
        -0.57887049, -1.0008494 ],
       [-0.50157819,  1.97958889, -0.5015119 , ..., -0.5476947 ,
         1.13129679,  0.99915132],
       [-0.50157819, -0.50515539, -0.5015119 , ..., -0.92985224,
        -2.08891182,  0.99915132]])

In [14]:
x_test

array([[-0.50157819,  1.97958889, -0.5015119 , ..., -0.48400178,
        -0.01487915,  0.99915132],
       [-0.50157819,  1.97958889, -0.5015119 , ...,  0.56448172,
         1.08884583, -1.0008494 ],
       [-0.50157819, -0.50515539, -0.5015119 , ...,  0.96133763,
         1.28897179,  0.99915132],
       ...,
       [-0.50157819, -0.50515539, -0.5015119 , ...,  3.36207088,
         0.12460258,  0.99915132],
       [-0.50157819, -0.50515539,  1.99397063, ...,  0.92214198,
        -0.22713396,  0.99915132],
       [-0.50157819, -0.50515539, -0.5015119 , ..., -0.92985224,
         1.75593236, -1.0008494 ]])

In [15]:
y_train

array([0, 0, 0, ..., 1, 1, 0])

In [16]:
import tensorflow as tf

In [17]:
ann = tf.keras.models.Sequential()

In [18]:
ann.add(tf.keras.layers.Dense(units=5,activation="relu"))

In [19]:
ann.add(tf.keras.layers.Dense(units=5,activation="relu"))

In [20]:
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

In [21]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [22]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
737/737 ━━━━━━━━━━━━━━━━━━━━ 1s 237us/step - accuracy: 0.5038 - loss: 0.6985
Epoch 2/100
737/737 ━━━━━━━━━━━━━━━━━━━━ 0s 224us/step - accuracy: 0.5021 - loss: 0.6941
Epoch 3/100
737/737 ━━━━━━━━━━━━━━━━━━━━ 0s 224us/step - accuracy: 0.4947 - loss: 0.6937
Epoch 4/100
737/737 ━━━━━━━━━━━━━━━━━━━━ 0s 225us/step - accuracy: 0.5124 - loss: 0.6932
Epoch 5/100
737/737 ━━━━━━━━━━━━━━━━━━━━ 0s 223us/step - accuracy: 0.5028 - loss: 0.6933
Epoch 6/100
737/737 ━━━━━━━━━━━━━━━━━━━━ 0s 224us/step - accuracy: 0.5085 - loss: 0.6931
Epoch 7/100
737/737 ━━━━━━━━━━━━━━━━━━━━ 0s 222us/step - accuracy: 0.5097 - loss: 0.6930
Epoch 8/100
737/737 ━━━━━━━━━━━━━━━━━━━━ 0s 226us/step - accuracy: 0.5143 - loss: 0.6927
Epoch 9/100
737/737 ━━━━━━━━━━━━━━━━━━━━ 0s 226us/step - accuracy: 0.5099 - loss: 0.6930
Epoch 10/100
737/737 ━━━━━━━━━━━━━━━━━━━━ 0s 224us/step - accuracy: 0.5100 - loss: 0.6927
Epoch 11/100
737/737 ━━━━━━━━━━━━━━━━━━━━ 0s 234us/step - accuracy: 0.5176 - loss: 0.6924
Epoch 12/100
737/73

737/737 ━━━━━━━━━━━━━━━━━━━━ 0s 228us/step - accuracy: 0.5216 - loss: 0.6916
Epoch 68/100
737/737 ━━━━━━━━━━━━━━━━━━━━ 0s 225us/step - accuracy: 0.5190 - loss: 0.6919
Epoch 69/100
737/737 ━━━━━━━━━━━━━━━━━━━━ 0s 224us/step - accuracy: 0.5172 - loss: 0.6920
Epoch 70/100
737/737 ━━━━━━━━━━━━━━━━━━━━ 0s 225us/step - accuracy: 0.5220 - loss: 0.6913
Epoch 71/100
737/737 ━━━━━━━━━━━━━━━━━━━━ 0s 229us/step - accuracy: 0.5217 - loss: 0.6914
Epoch 72/100
737/737 ━━━━━━━━━━━━━━━━━━━━ 0s 225us/step - accuracy: 0.5229 - loss: 0.6918
Epoch 73/100
737/737 ━━━━━━━━━━━━━━━━━━━━ 0s 224us/step - accuracy: 0.5207 - loss: 0.6917
Epoch 74/100
737/737 ━━━━━━━━━━━━━━━━━━━━ 0s 224us/step - accuracy: 0.5247 - loss: 0.6913
Epoch 75/100
737/737 ━━━━━━━━━━━━━━━━━━━━ 0s 223us/step - accuracy: 0.5172 - loss: 0.6921
Epoch 76/100
737/737 ━━━━━━━━━━━━━━━━━━━━ 0s 222us/step - accuracy: 0.5182 - loss: 0.6920
Epoch 77/100
737/737 ━━━━━━━━━━━━━━━━━━━━ 0s 223us/step - accuracy: 0.5201 - loss: 0.6919
Epoch 78/100
737/737 ━━

In [23]:
print(ann.predict(sc.transform([[0,0,0,0,1,13,100,70,1]]))>0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
[[ True]]


In [24]:
print(ann.predict(sc.transform([[0,0,0,0,1,13,100,70,1]])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
[[0.5042879]]


In [25]:
print(ann.predict(sc.transform([[0,0,0,1,1,24,100,67,1]]))>0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
[[False]]


In [27]:
print(ann.predict(sc.transform([[0,0,0,1,1,24,100,67,1]])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
[[0.49681512]]
